[directory]
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "

[git_status]
prefix = ""
suffix = " "

[time]
disabled = false
format = "%T"

[nodejs]
symbol = " "

[python]
symbol = " "

[package]
symbol = " "

[java]
symbol = " "

[golang]
symbol = " "

[rust]
symbol = " "
